### ISSUE TITLE
Threat in the chat.

### ISSUE THREAD

**Issue by TIGJERUX** [ElvUI-TBC/ElvUI#210]
https://gyazo.com/256f44da00bfe3ae8cf20f814c8ac33d 

I have omen enabled, This thing is there tho.

**Comment by crumdidlyumshis** [comment]
You must download the Threat 2.0 Library which will enable the threat feature. Due to the lack of default functions Blizzard provided via WotLK 3.0+, it was difficult to gather this information for threat. In TBC and Vanilla, this was only possible to gather threat via reading the combat log. Doing so made it possible, yet not 100% as a true function blizzard would have provided later on.

TL; DR

Download the addon: https://www.wowace.com/projects/threat-2-0/files?filter-game-version=2020709689%3A41
You should be good to go 👍

**Comment by TIGJERUX** [comment]
Threat 2.0 does not really work for me, tried one of the first releases he made, the latest ones and something in the middle. :c

It does say in the settings that you could use omen too. :3
