### ISSUE TITLE
[Request / Bug (?)] Raid Markers don't work, also SwingBar port?

### ISSUE THREAD

**Issue by nadszeg** [ElvUI-TBC/ElvUI#268]
Hey! :) I recently stumbled across this port, and it's awesome, the only problem I had with it that the RaidMarkers port doesn't seem to work for me, it won't show up in the ElvUI settings, nor on the screen. Also, I have a request - if you can, will you port the SwingBar addon?

**Comment by crumdidlyumshis** [comment]
RaidMarkers bar will only show up if in party or raid for TBC because that is the only way you can mark anyone in this expansion. In Wrath they made it so that you could mark outside parties or raids. That addon should work perfectly. Swingbar on the other hand is something we might be able to backport.

**Comment by crumdidlyumshis** [comment]
Update to your SwingBar request: https://github.com/ElvUI-TBC/ElvUI_SwingBar

Enjoy!
