### ISSUE TITLE
Castbar bug

### ISSUE THREAD

**Issue by Dehcimal** [ElvUI-TBC/ElvUI#45]
When you're spamming a casting spell (lighning bolt / lesser healing wave) the cast bar will vanish at mid cast.

You can reproduce it as much as you want

**Comment by kinappy** [comment]
I cant replicate this. I tried on a priest with flash heal, holy paladin with flash heal and shaman healing wave.'
I spammed each one until I went oom, manu back up and repeat. I did this three times on each char and for me the bar does not vanish.

Has it been solved and I missed it?

**Comment by Dehcimal** [comment]
Hey, I tested yesterday the bug still occurred. I just spam shaman heals
since it was the class I was using

**Comment by DriedChicken** [comment]
As I was just playing, I was able to replicate this bug.
If you are casting a spell with a duration greater than 1.5 sec, it will hide the castbar if you press the spell key again after 1.5 sec, before the cast actually ends.


**I was debugging this quickly, and here is my explaination about how this works, and how to fix it:**

The blizzard api has several events for spellcasting, they share the prefix "UNIT_SPELLCAST_"
The elvui castbar is using the oUF library element castbar.lua, this element registers all the relevant "UNIT_SPELLCAST_" events and hooks them in order to modify their logic.
Now if you press the spell button again after 1.5 sec passed, the wow client sends the event "UNIT_SPELLCAST_SENT" again and again, one time for every key action you press before the spell ends, this could be a logic from the old wow client to synchronise the spell casting with the server or just a bug on their side.

What oUF does is adding logic to the UNIT_SPELLCAST_FAILED_QUIET event, the wow client throws this event in this case because the spell, trying to be sent, (SENT event) is being blocked by the ongoing cast action.
In the UNIT_SPELLCAST_FAILED_QUIET the oUF calls castbar:Hide(), this is where the castbar disappears during the cast.

**My solution:**
- add a type check on self.casting, this returns always true while a cast is currently in progress

To fix this, modify the file: \ElvUI\Libraries\oUF\elements\castbar.lua
Add after line 129, (first line of function UNIT_SPELLCAST_FAILED)
```LUA
if (type(self.casting) == "nil") then return end
```

It also would be good to add the same after line 101 (function UNIT_SPELLCAST_FAILED)

**Comment by crumdidlyumshis** [comment]
Thank you again @DriedChicken for explaining this and coming up with a solution :) It works now!
