### ISSUE TITLE
/who keeps popping up

### ISSUE THREAD

**Issue by bluntdragonn** [ElvUI-TBC/ElvUI#454]
https://www.youtube.com/watch?v=3mMuAfgk8X8

**Comment by VideoPlayerCode** [comment]
This is because of LibWho/WhoLib which some addons use, to queue /who requests secretly.

Culprits (that I know about):
- Carbonite
- [CallToArms](https://github.com/ElvUI-TBC/ElvUI_AddOnSkins/issues/34)

It's not an ElvUI issue. Check and disable your other addons until you find which one causes this and then disable it.

**Comment by VideoPlayerCode** [comment]
Oh and I also remembered: Many private servers throttle /who requests VERY heavily.

LibWho was not written for private servers.

So if you type `/who <something>`, your server may not reply, and you'll see a yellow text message saying something like "Request for /who "blah" timed out, queuing and retrying...". And it will repeatedly time out and retry over and over (and open the /who window several times).

This is because LibWho expects Blizzard's timeout values/throttling rates, not the extreme private server rates.

But in your video it doesn't look like you've done a /who request manually.

So in your case it's an addon causing it. Try to disable all except `ElvUI`, `!Compatibility` and `!DebugTools`. The issue will go away. Then keep enabling addons one by one until the problem appears again. Then you know what caused it.

**Comment by Apollyonn** [comment]
#299
