### ISSUE TITLE
Help Wanted!

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-TBC/ElvUI#68]
Something I normally wouldn't do is post topics like this. But here I am posting it anyway. An increase in population of this addon has taken effect and the increase in bugs is arising more rapidly than before.

I personally have had very little time lately to invest into this project and it seems as though I cannot keep up with the amount of issues being posted. @Bunny67, @Loaal, @Apollyonn, and others are busy with their own projects and personal life so their time is limited as well; I will never expect or demand anything of them or anybody for that matter.

Having a background in web development, I lack some knowledge and skills in LUA and the WoW API. I want to learn more about LUA, I want to fix more, I have the drive, but not the time at the moment. I'm not here to say I give up (I will never give up). This is something I do on the side for fun when I have time! 💃 

I am here reaching out to anyone who has any knowledge in LUA, TBC WoW API, or any background in development, to pull a local git of this repository onto your machine and see if you can tackle any of the issues remaining. Send us your PR's or Pastebins or w/e you want to use to help out in developing this awesome UI for TBC. 

I always laughed 😆 when I read the last comment on this topic: http://www.tukui.org/forums/topic.php?id=24363 

> Question: **Elvui for wow TBC 2.4.3? is it possible?**

> Answer: No it is not possible.

Well, **_it is possible_**, and it is awesome to have it now. So lets make this UI as perfect as it can be! 🥇

**Comment by Bunny67** [comment]
i playing in legion :(

**Comment by crumdidlyumshis** [comment]
No worries @Bunny67! Without your initial help, this project wouldn't exist! Thank you! Nothing should be expected of anyone. We all have personal lives. Maybe when you get bored of legion, you might have a spurt of energy to add a few updates to this :D haha

**Comment by Healsonheels** [comment]
I really considered not playing on Outland because I was not able to get an UI that I was confortable with. After playing on Lordaeron with ElvUI (My UI: http://i.imgur.com/HnrXzHW.jpg) - Days ago I googled ElvUI 2.4.3 and I did not find anything, only the TukUI forum that @crumdidlyumshis linked. Then, after 2 days of trying to make an UI with 100 addons configured, or trying UI Suites, etcetera, I googled ElvUI for the burning crusade, expecting a miracle, and if not, I was going to go back to Lordaeron, I am already using ElvUI for TBC, will start adding little addons and configuring slowly while playing. I stopped playing at the moment because of the Chat error popup, and wanted to see how to report bugs or how could players help. I will check this pages later. Bye :)
